name: Flutter CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v3
        with:
          flutter-version: "3.27.0"
      - name: Install dependencies
        run: flutter pub get
      - name: Build Apk
        run: flutter build apk --release
      - name: Upload Apk
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk

  ios:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v3
        with:
          flutter-version: "3.27.0"
      - name: Install dependencies
        run: flutter pub get
      - name: Build iOS App
        run: flutter build ios --release --no-codesign
      - name: Upload iOS App
        uses: actions/upload-artifact@v3
        with:
          name: ios-ipa
          path: build/ios/ipa/*.ipa
