name: Flutter CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create .env file from secrets
        run: |
          echo "API_URL=${{ secrets.API_URL }}" > .env
          echo "API_KEY=${{ secrets.API_KEY }}" >> .env
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Check java version
        run: java -version
      - name: Print JAVA_HOME
        run: echo $JAVA_HOME
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.0"
      - name: Flutter doctor verbose
        run: flutter doctor -v
      - name: Install dependencies
        run: flutter pub get
      - name: Build Apk
        run: flutter build apk --release
        env:
          JAVA_HOME: ${{ env.JAVA_HOME }}
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ env.BRANCH_NAME }}-release-apk
          path: build/app/outputs/flutter-apk/app-${{ env.BRANCH_NAME }}-release.apk

  ios:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create .env file from secrets
        run: |
          echo "API_URL=${{ secrets.API_URL }}" > .env
          echo "API_KEY=${{ secrets.API_KEY }}" >> .env
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.0"
      - name: Install dependencies
        run: flutter pub get
      - name: Build iOS App
        run: flutter build ios --release --no-codesign
      - name: Upload iOS App
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: build/ios/ipa/*.ipa
